name: AutoTool
main: com.WildAmazing.marinating.AutoTool.AutoTool
author: [Gravypod,marinating]
version: 1.5
commands:
   autotool:
      description: Auto swap items into your hotbar!
      usage:
           /autotool [on/off]
      aliases:
        - at