name: AutoTool
main: com.WildAmazing.marinating.AutoTool.AutoTool
version: 1.4
commands:
   autotool:
      description: Auto swap items into your hotbar!
      usage:
           /autotool [on/off]
      aliases:
        - at